---
- name: kubeadm init
  shell: |
    sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ groups['master'][0] }}

- name: get kubeadm token
  shell: |
    kubeadm token list | awk '{print $1}' | awk 'FNR == 2 {print}'
  register: K8S_TOKEN
- debug:
    msg: "{{ K8S_TOKEN.stdout }}"


- name: get kubeadm cert hash
  shell: |
    openssl x509 -in /etc/kubernetes/pki/ca.crt -noout -pubkey | openssl rsa -pubin -outform DER 2>/dev/null | sha256sum | cut -d' ' -f1
  register: K8S_MASTER_CA_HASH
- debug:
    msg: "{{ K8S_MASTER_CA_HASH.stdout }}"


- name: "Add K8S Token and Hash to dummy host"
  add_host:
    name: "K8S_TOKEN_HOLDER"
    token: "{{ K8S_TOKEN }}"
    hash: "{{ K8S_MASTER_CA_HASH }}"

- name: create .kube directory
  file:
    path: /home/master/.kube
    state: directory

- name: copy admin.conf to /.kube
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /home/master/.kube/config

- name: change usergroup of config file
  file:
    path: /home/master/.kube/config
    owner: master
    group: master
