---
- name: setup alma VM for full stack dev
  become: yes
  hosts: all
  remote_user: nik
  roles:
    - {role: mysql, tags: ['db']}
    - {role: mongo, tags: ['db']}
    - {role: docker, tags: ['docker']}