---
- name: k8 setup master
  become: yes
  hosts: master
  remote_user: master
  roles:
    - kubeadm

- name: k8 setup worker1
  become: yes
  hosts: worker1
  remote_user: worker1
  roles:
    - kubeadm

- name: k8 setup worker2
  become: yes
  hosts: worker2
  remote_user: worker2
  roles:
    - kubeadm

- name: k8 init only on master
  become: yes
  hosts: master
  remote_user: master
  roles:
    - kubeadm_init

- name: k8 setup token on worker1
  become: yes
  hosts: worker1
  remote_user: worker1
  roles:
    - join_nodes

- name: k8 setup token on worker2
  become: yes
  hosts: worker2
  remote_user: worker2
  roles:
    - join_nodes
