---
- name: install dependencies
  become: yes
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest
    update_cache: true

- name: adding GPG keys
  become: yes
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: add in repository
  become: yes
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: apt update 
  become: yes
  apt:
    update_cache: true

- name: install docker and all docker stuff
  become: yes
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    state: latest
    update_cache: true

- name: adding docker to sudo
  become: yes
  shell: |
    sudo chgrp docker $(which docker)
    sudo chmod g+s $(which docker)

  